title: Shiran Zhang
description: I'm a senior undergraduate student in Peking University, studying Computer Science and Philosophy.
logo: /assets/img/me.jpg
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag